---
name: "JellyFederation"
guid: "e5c0cda1-805e-41e2-9654-e17143dc31a1"
version: "1.1.1.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "lukasschachner"
overview: "Federation media sharing between Jellyfin servers"
description: "Federation media sharing between Jellyfin servers"
category: "General"
artifacts:
  - "JellyFederation.Plugin.dll"
  - "JellyFederation.Shared.dll"
changelog: |-
  - Initial plugin packaging manifest.
