// <auto-generated />
using System;
using JellyFederation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JellyFederation.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(FederationDbContext))]
    partial class FederationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("JellyFederation.Shared.Models.FileRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailureCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("JellyfinItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwningServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestingServerId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedTransportMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TransferStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransportSelectionReason")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwningServerId");

                    b.HasIndex("RequestingServerId");

                    b.ToTable("FileRequests");
                });

            modelBuilder.Entity("JellyFederation.Shared.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromServerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ToServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromServerId");

                    b.HasIndex("ToServerId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("JellyFederation.Shared.Models.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequestable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JellyfinItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "Title");

                    b.HasIndex("ServerId", "Type");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("JellyFederation.Shared.Models.RegisteredServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("JellyFederation.Shared.Models.FileRequest", b =>
                {
                    b.HasOne("JellyFederation.Shared.Models.RegisteredServer", "OwningServer")
                        .WithMany()
                        .HasForeignKey("OwningServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JellyFederation.Shared.Models.RegisteredServer", "RequestingServer")
                        .WithMany()
                        .HasForeignKey("RequestingServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwningServer");

                    b.Navigation("RequestingServer");
                });

            modelBuilder.Entity("JellyFederation.Shared.Models.Invitation", b =>
                {
                    b.HasOne("JellyFederation.Shared.Models.RegisteredServer", "FromServer")
                        .WithMany("SentInvitations")
                        .HasForeignKey("FromServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JellyFederation.Shared.Models.RegisteredServer", "ToServer")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ToServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromServer");

                    b.Navigation("ToServer");
                });

            modelBuilder.Entity("JellyFederation.Shared.Models.MediaItem", b =>
                {
                    b.HasOne("JellyFederation.Shared.Models.RegisteredServer", "Server")
                        .WithMany("MediaItems")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("JellyFederation.Shared.Models.RegisteredServer", b =>
                {
                    b.Navigation("MediaItems");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentInvitations");
                });
#pragma warning restore 612, 618
        }
    }
}
