name: "Build Plugin"

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
          global-json-file: global.json

      - name: Build
        run: |
          dotnet publish src/JellyFederation.Plugin/JellyFederation.Plugin.csproj \
            --configuration Release \
            --output dist/
